### ISSUE TITLE
NPE: Failed to handle packet tweed:sync_config

### ISSUE THREAD

**Issue by sargunv** [Siphalor/tweed-api#1]
Got this when I installed Mouse Wheelie. Full log: https://paste.ee/p/FOkwO

```
[13:25:31] [Netty Local Client IO #1/WARN]: Failed to handle packet tweed:sync_config!
java.lang.NullPointerException: null
	at de.siphalor.tweed.config.ConfigFile.read(ConfigFile.java:236) ~[a5431057-8463-4d9c-b494-59289cbd1f48.jar:?]
	at de.siphalor.tweed.client.ClientCore.lambda$onInitializeClient$2(ClientCore.java:47) ~[a5431057-8463-4d9c-b494-59289cbd1f48.jar:?]
	at net.fabricmc.fabric.impl.network.PacketRegistryImpl.accept(PacketRegistryImpl.java:164) [ae9ca247-d84c-40b8-92e1-219cd5ca6014.jar:?]
	at net.fabricmc.fabric.impl.network.ClientSidePacketRegistryImpl.accept(ClientSidePacketRegistryImpl.java:100) [ae9ca247-d84c-40b8-92e1-219cd5ca6014.jar:?]
	at net.minecraft.class_634.handler$onCustomPayload$zzd000(class_634.java:2293) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:62) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:10) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:159) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:150) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:54) [intermediary-minecraft-1.14.1-client.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:304) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:446) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:51) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:404) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Siphalor** [comment]
Should be fixed ;)
